# Generated by Django 5.1.7 on 2025-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_speed_down', models.IntegerField(blank=True)),
                ('alt_speed_enabled', models.BooleanField()),
                ('alt_speed_time_begin', models.IntegerField(blank=True)),
                ('alt_speed_time_day', models.IntegerField(blank=True)),
                ('alt_speed_time_enabled', models.BooleanField()),
                ('alt_speed_time_end', models.IntegerField(blank=True)),
                ('alt_speed_up', models.IntegerField(blank=True)),
                ('bind_address_ipv4', models.GenericIPAddressField()),
                ('bind_address_ipv6', models.GenericIPAddressField()),
                ('blocklist_enabled', models.BooleanField()),
                ('blocklist_url', models.URLField(max_length=300)),
                ('cache_size_mb', models.IntegerField(blank=True)),
                ('dht_enabled', models.BooleanField()),
                ('download_dir', models.CharField(blank=True, max_length=200)),
                ('download_queue_enabled', models.BooleanField()),
                ('download_queue_size', models.IntegerField(blank=True)),
                ('encryption', models.IntegerField(blank=True)),
                ('idle_seeding_limit', models.IntegerField(blank=True)),
                ('idle_seeding_limit_enabled', models.BooleanField()),
                ('incomplete_dir', models.CharField(blank=True, max_length=200)),
                ('incomplete_dir_enabled', models.BooleanField()),
                ('lpd_enabled', models.BooleanField()),
                ('message_level', models.IntegerField(blank=True)),
                ('peer_congestion_algorithm', models.CharField(blank=True, max_length=200)),
                ('peer_id_ttl_hours', models.IntegerField(blank=True)),
                ('peer_limit_global', models.IntegerField(blank=True)),
                ('peer_limit_per_torrent', models.IntegerField(blank=True)),
                ('peer_port', models.IntegerField(blank=True)),
                ('peer_port_random_high', models.IntegerField(blank=True)),
                ('peer_port_random_low', models.IntegerField(blank=True)),
                ('peer_port_random_on_start', models.BooleanField()),
                ('peer_socket_tos', models.CharField(blank=True, max_length=200)),
                ('pex_enabled', models.BooleanField()),
                ('port_forwarding_enabled', models.BooleanField()),
                ('preallocation', models.IntegerField(blank=True)),
                ('prefetch_enabled', models.IntegerField(blank=True)),
                ('queue_stalled_enabled', models.BooleanField()),
                ('queue_stalled_minutes', models.IntegerField(blank=True)),
                ('ratio_limit', models.IntegerField(blank=True)),
                ('ratio_limit_enabled', models.BooleanField()),
                ('rename_partial_files', models.BooleanField()),
                ('rpc_authentication_required', models.BooleanField()),
                ('rpc_bind_address', models.GenericIPAddressField()),
                ('rpc_enabled', models.BooleanField()),
                ('rpc_password', models.CharField(blank=True, max_length=200)),
                ('rpc_port', models.IntegerField(blank=True)),
                ('rpc_url', models.CharField(blank=True, max_length=200)),
                ('rpc_username', models.CharField(blank=True, max_length=200)),
                ('rpc_whitelist', models.CharField(blank=True, max_length=200)),
                ('rpc_whitelist_enabled', models.BooleanField()),
                ('scrape_paused_torrents_enabled', models.BooleanField()),
                ('script_torrent_done_enabled', models.BooleanField()),
                ('script_torrent_done_filename', models.CharField(blank=True, max_length=200)),
                ('seed_queue_enabled', models.BooleanField()),
                ('seed_queue_size', models.IntegerField(blank=True)),
                ('speed_limit_down', models.IntegerField(blank=True)),
                ('speed_limit_down_enabled', models.BooleanField()),
                ('speed_limit_up', models.IntegerField(blank=True)),
                ('speed_limit_up_enabled', models.BooleanField()),
                ('start_added_torrents', models.BooleanField()),
                ('trash_original_torrent_files', models.BooleanField()),
                ('umask', models.IntegerField(blank=True)),
                ('upload_slots_per_torrent', models.IntegerField(blank=True)),
                ('utp_enabled', models.BooleanField()),
                ('watch_dir', models.CharField(blank=True, max_length=200)),
                ('watch_dir_enabled', models.BooleanField()),
                ('open_file_limit', models.IntegerField(blank=True, default=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AutoTorrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=300)),
                ('excludes', models.ManyToManyField(blank=True, to='dashboard.excludes')),
            ],
        ),
    ]
