# Generated by Django 5.1.7 on 2025-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Inclusions',
                'verbose_name_plural': 'Inclusions',
            },
        ),
        migrations.AlterModelOptions(
            name='autotorrent',
            options={'verbose_name': 'Automatically Torrent', 'verbose_name_plural': 'Automatically Torrent'},
        ),
        migrations.AlterModelOptions(
            name='excludes',
            options={'verbose_name': 'Exclusions', 'verbose_name_plural': 'Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='transmissionsetting',
            options={'verbose_name': 'Transmission Settings', 'verbose_name_plural': 'Transmission Settings'},
        ),
    ]
