# Generated by Django 5.1.7 on 2025-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_includes_alter_autotorrent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotorrent',
            name='includes',
            field=models.ManyToManyField(blank=True, to='dashboard.includes'),
        ),
    ]
