# Generated by Django 5.1.7 on 2025-03-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_autotorrent_includes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmissionsetting',
            name='open_file_limit',
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='download_limit',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='download_limit_enabled',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='max_peers_global',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='rpc_host_whitelist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='rpc_host_whitelist_enabled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='upload_limit',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='upload_limit_enabled',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
