# Generated by Django 5.1.7 on 2025-03-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_transmissionsetting_open_file_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionsetting',
            name='prefetch_enabled',
            field=models.BooleanField(),
        ),
    ]
