# Generated by Django 5.1.7 on 2025-03-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_transmissionsetting_prefetch_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissionsetting',
            name='torrentfiles_dir',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transmissionsetting',
            name='torrentfiles_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
